AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: personal-inventory-mngr

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetInventory:
          Type: Api
          Properties:
            Path: /get
            Method: get
            RestApiId: !Ref ServerlessRestApi  # Add this line to link to the API
            Proxy: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: put/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        PutInventory:
          Type: Api
          Properties:
            Path: /put
            Method: put
            RestApiId: !Ref ServerlessRestApi  # Add this line to link to the API
            Proxy: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'personal-inventory'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"

Outputs:
  GetInventoryApi:
    Description: API Gateway endpoint URL for Prod stage for GetInventory function
    Value: !Sub "https://j45kvnew6d.execute-api.us-east-1.amazonaws.com/Prod/get"

  GetFunctionArn:
    Description: Get Inventory Lambda Function ARN
    Value: !GetAtt GetFunction.Arn

  PutFunctionArn:
    Description: Put Inventory Lambda Function ARN
    Value: !GetAtt PutFunction.Arn
