name: Deploy with AWS SAM

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.12.5

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step to check out the repository
      - uses: actions/checkout@v3

      # Set up Python environment with the correct version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Debug Secrets
      - name: Debug Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID set: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
          echo "AWS_SESSION_TOKEN set: ${{ secrets.AWS_SESSION_TOKEN != '' }}"
          echo "AWS_REGION set: ${{ secrets.AWS_REGION != '' }}"

      # Install AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
          if ! command -v sam &> /dev/null; then
            curl -sSL https://raw.githubusercontent.com/aws/aws-sam-cli/main/packaging/samcli-brew-install | bash -s -- --update
          fi

      # Deploy with AWS SAM
      - name: Deploy with AWS SAM
        run: |
          sam deploy --no-confirm-changeset --region ${{ secrets.AWS_REGION }} --no-session
